# Generated by Django 3.0.5 on 2020-06-04 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media')),
                ('title', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(null=True)),
                ('date', models.DateField(db_index=True)),
                ('time', models.TimeField(db_index=True)),
            ],
            options={
                'db_table': 'theater_performance',
                'index_together': {('date', 'time'), ('title',), ('date',)},
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('number', models.PositiveIntegerField(db_index=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('name', models.CharField(db_index=True, max_length=30, unique=True)),
            ],
            options={
                'index_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('available', models.BooleanField(default=True)),
                ('performance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='theater.Performance')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theater.Price')),
                ('row', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theater.Row')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theater.Seat')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='theater.Sector')),
            ],
            options={
                'unique_together': {('performance', 'sector', 'row', 'seat')},
            },
        ),
    ]
