# Generated by Django 3.0.5 on 2020-06-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performance',
            options={'ordering': ('date',)},
        ),
        migrations.AlterField(
            model_name='performance',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='performance/'),
        ),
    ]
