# Generated by Django 3.0.5 on 2020-06-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20200604_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('new', 'Новый'), ('in the execution', 'В исполнении'), ('completed', 'Завершен'), ('denied', 'Отклонен')], db_index=True, max_length=20),
        ),
    ]
