# Generated by Django 3.0.5 on 2020-06-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_auto_20200606_2311'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-id',)},
        ),
        migrations.AlterField(
            model_name='status',
            name='name',
            field=models.CharField(choices=[('new', 'Новый'), ('in the execution', 'В исполнении'), ('completed', 'Завершен'), ('rejected', 'Отклонен')], db_index=True, max_length=20),
        ),
    ]
